# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import training_pb2 as training__pb2
from . import utils_pb2 as utils__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in training_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/training.Training/ListDevices',
                request_serializer=utils__pb2.Empty.SerializeToString,
                response_deserializer=utils__pb2.Devices.FromString,
                _registered_method=True)
        self.Init = channel.unary_unary(
                '/training.Training/Init',
                request_serializer=training__pb2.TrainingConfig.SerializeToString,
                response_deserializer=training__pb2.TrainingSessionId.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/training.Training/Start',
                request_serializer=training__pb2.TrainingSessionId.SerializeToString,
                response_deserializer=utils__pb2.Empty.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/training.Training/Resume',
                request_serializer=training__pb2.TrainingSessionId.SerializeToString,
                response_deserializer=utils__pb2.Empty.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/training.Training/Pause',
                request_serializer=training__pb2.TrainingSessionId.SerializeToString,
                response_deserializer=utils__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamUpdates = channel.unary_stream(
                '/training.Training/StreamUpdates',
                request_serializer=training__pb2.TrainingSessionId.SerializeToString,
                response_deserializer=training__pb2.StreamUpdateResponse.FromString,
                _registered_method=True)
        self.GetLogs = channel.unary_unary(
                '/training.Training/GetLogs',
                request_serializer=training__pb2.TrainingSessionId.SerializeToString,
                response_deserializer=training__pb2.GetLogsResponse.FromString,
                _registered_method=True)
        self.GetBestModelIdx = channel.unary_stream(
                '/training.Training/GetBestModelIdx',
                request_serializer=training__pb2.TrainingSessionId.SerializeToString,
                response_deserializer=training__pb2.GetBestModelIdxResponse.FromString,
                _registered_method=True)
        self.Save = channel.unary_unary(
                '/training.Training/Save',
                request_serializer=training__pb2.SaveRequest.SerializeToString,
                response_deserializer=utils__pb2.Empty.FromString,
                _registered_method=True)
        self.Export = channel.unary_unary(
                '/training.Training/Export',
                request_serializer=training__pb2.ExportRequest.SerializeToString,
                response_deserializer=utils__pb2.Empty.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/training.Training/Predict',
                request_serializer=training__pb2.PredictRequest.SerializeToString,
                response_deserializer=training__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/training.Training/GetStatus',
                request_serializer=training__pb2.TrainingSessionId.SerializeToString,
                response_deserializer=training__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.CloseTrainerSession = channel.unary_unary(
                '/training.Training/CloseTrainerSession',
                request_serializer=training__pb2.TrainingSessionId.SerializeToString,
                response_deserializer=utils__pb2.Empty.FromString,
                _registered_method=True)


class TrainingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBestModelIdx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseTrainerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=utils__pb2.Empty.FromString,
                    response_serializer=utils__pb2.Devices.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=training__pb2.TrainingConfig.FromString,
                    response_serializer=training__pb2.TrainingSessionId.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=training__pb2.TrainingSessionId.FromString,
                    response_serializer=utils__pb2.Empty.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=training__pb2.TrainingSessionId.FromString,
                    response_serializer=utils__pb2.Empty.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=training__pb2.TrainingSessionId.FromString,
                    response_serializer=utils__pb2.Empty.SerializeToString,
            ),
            'StreamUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUpdates,
                    request_deserializer=training__pb2.TrainingSessionId.FromString,
                    response_serializer=training__pb2.StreamUpdateResponse.SerializeToString,
            ),
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=training__pb2.TrainingSessionId.FromString,
                    response_serializer=training__pb2.GetLogsResponse.SerializeToString,
            ),
            'GetBestModelIdx': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBestModelIdx,
                    request_deserializer=training__pb2.TrainingSessionId.FromString,
                    response_serializer=training__pb2.GetBestModelIdxResponse.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=training__pb2.SaveRequest.FromString,
                    response_serializer=utils__pb2.Empty.SerializeToString,
            ),
            'Export': grpc.unary_unary_rpc_method_handler(
                    servicer.Export,
                    request_deserializer=training__pb2.ExportRequest.FromString,
                    response_serializer=utils__pb2.Empty.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=training__pb2.PredictRequest.FromString,
                    response_serializer=training__pb2.PredictResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=training__pb2.TrainingSessionId.FromString,
                    response_serializer=training__pb2.GetStatusResponse.SerializeToString,
            ),
            'CloseTrainerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseTrainerSession,
                    request_deserializer=training__pb2.TrainingSessionId.FromString,
                    response_serializer=utils__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'training.Training', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('training.Training', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Training(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/ListDevices',
            utils__pb2.Empty.SerializeToString,
            utils__pb2.Devices.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/Init',
            training__pb2.TrainingConfig.SerializeToString,
            training__pb2.TrainingSessionId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/Start',
            training__pb2.TrainingSessionId.SerializeToString,
            utils__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/Resume',
            training__pb2.TrainingSessionId.SerializeToString,
            utils__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/Pause',
            training__pb2.TrainingSessionId.SerializeToString,
            utils__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/training.Training/StreamUpdates',
            training__pb2.TrainingSessionId.SerializeToString,
            training__pb2.StreamUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/GetLogs',
            training__pb2.TrainingSessionId.SerializeToString,
            training__pb2.GetLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBestModelIdx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/training.Training/GetBestModelIdx',
            training__pb2.TrainingSessionId.SerializeToString,
            training__pb2.GetBestModelIdxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/Save',
            training__pb2.SaveRequest.SerializeToString,
            utils__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Export(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/Export',
            training__pb2.ExportRequest.SerializeToString,
            utils__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/Predict',
            training__pb2.PredictRequest.SerializeToString,
            training__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/GetStatus',
            training__pb2.TrainingSessionId.SerializeToString,
            training__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseTrainerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.Training/CloseTrainerSession',
            training__pb2.TrainingSessionId.SerializeToString,
            utils__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
