repos:
- repo: https://github.com/ambv/black
  rev: 22.1.0
  hooks:
  - id: black
    language_version: python3.7
    exclude: (.*_pb2.py|.*_pb2_grpc.py)
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
