repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
    exclude: (.*_pb2.py|.*_pb2_grpc.py)
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.1
  hooks:
    - id: isort
