# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_store_pb2 as data__store__pb2


class DataStoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Upload = channel.stream_unary(
        '/DataStore/Upload',
        request_serializer=data__store__pb2.UploadRequest.SerializeToString,
        response_deserializer=data__store__pb2.UploadResponse.FromString,
        )
    self.Remove = channel.unary_unary(
        '/DataStore/Remove',
        request_serializer=data__store__pb2.RemoveRequest.SerializeToString,
        response_deserializer=data__store__pb2.RemoveResponse.FromString,
        )


class DataStoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Upload(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Remove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataStoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Upload': grpc.stream_unary_rpc_method_handler(
          servicer.Upload,
          request_deserializer=data__store__pb2.UploadRequest.FromString,
          response_serializer=data__store__pb2.UploadResponse.SerializeToString,
      ),
      'Remove': grpc.unary_unary_rpc_method_handler(
          servicer.Remove,
          request_deserializer=data__store__pb2.RemoveRequest.FromString,
          response_serializer=data__store__pb2.RemoveResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DataStore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
