numpy:
  - 1.12
python:
  - 3.6
tifffile:
  - 0.4.post2
package_name:
  - tiktorch-cpu
  - tiktorch
pytorch_flavor:
  - pytorch-cpu
  - pytorch
inferno_flavor:
  - inferno-cpu
  - inferno
pytorch_version:
  - 0.4.1
inferno_version:
  - 0.2
zip_keys:
  - package_name
  - pytorch_flavor
  - inferno_flavor
