# changed the recipe to be client, server at the same time
# add pytorch (or other NN libraries, see bioimageio.core) to enable server
# capabilities.
# Add git, inferno, pytorch!
{% set setup_py_data = load_setup_py_data() %}

package:
  name: tiktorch

  version: {{ setup_py_data['version'] }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - tiktorch-server = tiktorch.server.base:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pickle5  # [py37]
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run_constrained:
    - cudatoolkit >=10.2
    - mkl <2024.1.0
    {% for dep in setup_py_data['extras_require']['server-pytorch'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in setup_py_data['extras_require']['server-tensorflow'] %}
    - {{ dep.lower() }}
    {% endfor %}

about:
  home: https://github.com/ilastik/tiktorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Neural network server'
  doc_url: https://github.com/ilastik/tiktorch
  dev_url: https://github.com/ilastik/tiktorch

test:
  requires:
    {% for dep in setup_py_data['extras_require']['server-pytorch'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in setup_py_data['extras_require']['server-tensorflow'] %}
    - {{ dep.lower() }}
    {% endfor %}
    # this is still necessary, torchvision doesn't work properly with cpuonly mutex
    - torchvision=*=*cpu
    - cpuonly
  imports:
    # client
    - tiktorch
    - tiktorch.proto.inference_pb2
    - tiktorch.proto.inference_pb2_grpc
    - tiktorch.proto.data_store_pb2
    - tiktorch.proto.data_store_pb2_grpc
    - tiktorch.types
    - tiktorch.converters
    # server
    - tiktorch.server.base
    - tiktorch.server.session
