package:
  name: tiktorch
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version %}
  {% endif %}

  version:
   {{tagged_version}}

source:
  git_url: ../

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python -m pip install --no-deps --ignore-installed .
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}
  entry_points:
    - tiktorch-server = tiktorch.server.base:main

requirements:
  build:
    - pip
    - python >=3.7
  run:
    - h5py
    - python >=3.7
    - numpy >=1.14
    - python-bioimage-io
    - pytorch-bioimage-io
    - grpcio=1.16.0
    - protobuf=3.11.4
    - pyyaml
    - paramiko
    - inferno

test:
  imports:
    - tiktorch.server.base
    - tiktorch.server.training
