# changed the recipe to be client, server at the same time
# add pytorch (or other NN libraries, see bioimageio.core) to enable server
# capabilities.
# Add git, inferno, pytorch!
{% set setup_py_data = load_setup_py_data() %}

package:
  name: tiktorch

  version: {{ setup_py_data['version'] }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script:
    - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - tiktorch-server = tiktorch.server.base:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=40.0
    - setuptools_scm
  run:
    - python >=3.8
    {% for dep in setup_py_data['install_requires'] %}
      # for pytorch-3dunet the names on conda and pypi differ:
      {% if 'pytorch3dunet' in dep.lower() %}
    - {{ dep.lower().replace('pytorch3dunet', 'pytorch-3dunet') }}
      {% else %}
    - {{ dep.lower() }}
      {% endif %}
    {% endfor %}
  run_constrained:
    - mkl <2024.1.0  # [linux] until pytorch is compatible with the current version
    - cudatoolkit >=10.2
    {% for dep in setup_py_data['extras_require']['server-pytorch'] %}
    - {{ dep.lower() }}
    {% endfor %}

about:
  home: https://github.com/ilastik/tiktorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Neural network server'
  doc_url: https://github.com/ilastik/tiktorch
  dev_url: https://github.com/ilastik/tiktorch

test:
  requires:
    {% for dep in setup_py_data['extras_require']['server-pytorch'] %}
    - {{ dep.lower() }}
    {% endfor %}
    - python 3.9.*
    - pytest
    - pytest-grpc
    - pytest-timeout
    - cpuonly
    - ilastik-pytorch-version-helper-cpu
  imports:
    # client
    - tiktorch
    - tiktorch.proto.inference_pb2
    - tiktorch.proto.inference_pb2_grpc
    - tiktorch.proto.data_store_pb2
    - tiktorch.proto.data_store_pb2_grpc
    - tiktorch.types
    - tiktorch.converters
    # server
    - tiktorch.server.base
    - tiktorch.server.session

  source_files:
    - tests
    - tiktorch
    - pytest.ini

  commands:
    - pytest

