{% set setup_py_data = load_setup_py_data() %}
{% if not cpuonly is defined %}
  {% set cpuonly = 'none' %}
  {% set cudatoolkit = 'none' %}
{% endif %}

package:
  {% if cpuonly.startswith('none') %}
  name: tiktorch
  {% else %}
  name: tiktorch-cpu
  {% endif %}

  version: {{ setup_py_data['version'] }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - tiktorch-server = tiktorch.server.base:main

requirements:

  host:
    - pip
    - python >=3.7

  run:
    - python >=3.7
    {% if not cpuonly.startswith('none') %}
    - {{ cpuonly }}
    {% else %}
    - cudatoolkit >=10.2
    {% endif %}
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in setup_py_data['extras_require']['server'] %}
    - {{ dep.lower() }}
    {% endfor %}


about:
  home: https://github.com/ilastik/tiktorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Neural network server'
  doc_url: https://github.com/ilastik/tiktorch
  dev_url: https://github.com/ilastik/tiktorch

test:
  imports:
    - tiktorch.server.base
    - tiktorch.server.session
