package:
  name: pytorch-bioimage-io
  version: 0.1

source:
  git_url: https://github.com/bioimage-io/pytorch-bioimage-io
  git_rev: 02576f29e9c144d5bae68735fd10c9b7cf248859

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - pytorch >=1.3,<1.5
    - scikit-learn
    - marshmallow >=3.4,<3.5
    - python-bioimage-io
    - pyyaml
    - dataclasses >=0.6  # [py<37]

test:
  imports:
    - pybio.torch
    - pybio.torch.training

about:
  home: https://github.com/bioimage-io/pytorch-bioimage-io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pytorch related components of pybio'

  doc_url: https://github.com/bioimage-io/pytorch-bioimage-io
  dev_url: https://github.com/bioimage-io/pytorch-bioimage-io

extra:
  recipe-maintainers:
    - m-novikov
