package:
  name: python-bioimage-io
  version: 0.2

source:
  git_url: https://github.com/bioimage-io/python-bioimage-io
  git_rev: b44ff3b99fa2717dd0efea6932b6b07ea1a2b9af

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - scikit-learn
    - requests
    - marshmallow >=3.4,<3.5
    - git
    - pyyaml
    - ruamel.yaml
    - dataclasses >=0.6  # [py<37]

test:
  imports:
    - bioimageio.spec

about:
  home: https://github.com/bioimage-io/python-bioimage-io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Tools for parsing bioimageio model specification'

  doc_url: https://github.com/bioimage-io/python-bioimage-io
  dev_url: https://github.com/bioimage-io/python-bioimage-io

extra:
  recipe-maintainers:
    - m-novikov
