package:
  name: tiktorch-client
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version %}
  {% endif %}

  version: {{tagged_version}}

source:
  git_url: ../

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python -m pip install --no-deps --ignore-installed .
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}


requirements:
  build:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy >=1.14
    - grpcio >=1.23
    - protobuf=3.11.4
    - paramiko
    - pyyaml

about:
  home: https://github.com/ilastik/tiktorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Neural network server client'
  doc_url: https://github.com/ilastik/tiktorch
  dev_url: https://github.com/ilastik/tiktorch

test:
  imports:
    - tiktorch
    - tiktorch.proto.inference_pb2
    - tiktorch.proto.inference_pb2_grpc
    - tiktorch.proto.data_store_pb2
    - tiktorch.proto.data_store_pb2_grpc
