{% set setup_py_data = load_setup_py_data() %}
package:
  name: tiktorch-client
  version: {{ setup_py_data['version'] }}

source:
  path: ../

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}


about:
  home: https://github.com/ilastik/tiktorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Neural network server client'
  doc_url: https://github.com/ilastik/tiktorch
  dev_url: https://github.com/ilastik/tiktorch

test:
  imports:
    - tiktorch
    - tiktorch.proto.inference_pb2
    - tiktorch.proto.inference_pb2_grpc
    - tiktorch.proto.data_store_pb2
    - tiktorch.proto.data_store_pb2_grpc
    - tiktorch.types
    - tiktorch.converters

